server:
  port: 8091

domain:
  name: 127.0.0.1
#management.port=8092
spring:
  druid:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/houses?useUnicode=true&amp;amp;characterEncoding=UTF-8&amp;amp;zeroDateTimeBehavior=convertToNull&amp;amp;autoReconnect=true&amp;amp;rewriteBatchedStatements=true
    username: root
    password: 35541577
#druid\u75311.0.16\u5347\u7ea7\u52301.1.0,\u8fde\u63a5\u6c60\u914d\u7f6e\u8981\u6539\u6210maxActive,minIdle
    maxActive: 30
    minIdle: 5
    maxWait: 10000
    validationQuery: SELECT 'x'
#favicon
  favicon:
    enabled: false
#国际化配置
  messages:
    basename: messages/messages
    always-use-message-format: true
#    cache-seconds: 3600
    fallback-to-system-locale: false
    cache-duration: PT3600s
#freemarker配置
  freemarker:
    charset: utf-8
    content-type: text/html;charset=UTF-8
    expose-request-attributes: true
    expose-session-attributes: true
    #宏的属性
    expose-spring-macro-helpers: true
    suffix: .ftl

    settings:
      datetime_format: yyyy-MM-dd HH:mm:ss
      default_encoding: UTF-8
      auto_import: common/common.ftl as common
#httpclient
  httpclient:
    agent: agent
    connectTimeOut: 1000
    socketTimeOut: 10000
    maxConnTotal: 50
    maxConnPerRoute: 10
#设置上传文件大小
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB

  mail:
    username: No1Code@163.com
    host: smtp.163.com
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  oss:
    accessKeyId:
    accessKeySecret:
    bucketName: lp-houses
#md5盐
first:
  code:
    house:
      salt: firstcode
#文件保存路径
file:
 path: G:\upload
